# Generated by Django 3.0.6 on 2020-07-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=200, null=True)),
                ('product_id', models.CharField(max_length=100, null=True)),
                ('site_id', models.CharField(max_length=100, null=True)),
                ('cat_key', models.CharField(max_length=200, null=True)),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('category1', models.CharField(max_length=200, null=True)),
                ('category2', models.CharField(max_length=200, null=True)),
                ('category3', models.CharField(max_length=200, null=True)),
                ('category4', models.CharField(max_length=200, null=True)),
                ('p_key', models.CharField(max_length=200, null=True)),
                ('p_category', models.CharField(max_length=200, null=True)),
                ('click_url', models.CharField(max_length=200, null=True)),
                ('click_url_m', models.CharField(max_length=200, null=True)),
                ('product_price', models.CharField(max_length=40, null=True)),
                ('price_pc', models.CharField(max_length=200, null=True)),
                ('price_mobile', models.CharField(max_length=200, null=True)),
                ('brand', models.CharField(max_length=200, null=True)),
                ('import_flag', models.CharField(max_length=200, null=True)),
                ('save_path', models.CharField(max_length=100, null=True)),
                ('save_name', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField()),
                ('imp_cnt', models.IntegerField()),
                ('click_cnt', models.IntegerField()),
                ('cre_tt', models.DateTimeField()),
                ('appr_tt', models.DateTimeField()),
                ('rej_tt', models.DateTimeField()),
            ],
            options={
                'db_table': 'product_list',
            },
        ),
    ]
